### ISSUE TITLE
啥时候Release Inference Code and unofficial pre-trained weights呀，很急

### ISSUE THREAD

**Issue by s-yudi** [guoqincode/AnimateAnyone-unofficial#19]
急急急急

**Comment by guoqincode** [comment]
Due to the current shortage of GPU resources, I have only obtained preliminary results of the first stage, which proves that the current code is working, and I will train on a relatively large dataset when I have enough GPU resources.

If you have a lot of Gpus, I can guide you through the training.

**Comment by patrolli** [comment]
Hi, Could you share some fisrt phase tranining results?
